In [1]:
import torch

In [37]:
a=torch.tensor([[[1,2],[2,2],[3,3]],[[2,3],[3,3],[4,3]]])

In [41]:
test_a='ffjdlfd'
b=eval('test_a')

In [42]:
b

'ffjdlfd'

In [60]:
def test(a):
    print('aaaa'+a)
    return 1
    
a=False
b=test() if a else 0
b

0

In [57]:
from aiharness.fileutils import list_file,list_dir
list_dir('/usr')

['bin', 'standalone', 'libexec', 'sbin', 'local', 'lib', 'share']

In [58]:
((1,2),3)

((1, 2), 3)

In [61]:
s='fjdklfd'
eval('test(s)')

aaaafjdklfd


1

In [62]:
class AAA():
    def test(self,a):
        print('aaaa'+a)
        return 1
    def go(self):
        s='fjdklfdlf'
        eval('self.test(s)')     
AAA().go()

aaaafjdklfdlf


In [63]:
min(1,2,3,4)

1

In [64]:
max(-1,-1)

-1

In [70]:
min(-1,2,3,key=lambda i: i if i>0 else 9999)

2

In [71]:
"".find('1',0,1000)

-1

In [72]:
a=('1',1)

In [73]:
b=('2',2)

In [75]:
min(a,b,key=lambda i: i[1] if i[1]==1 else 0)

('2', 2)

In [76]:
a+b

('1', 1, '2', 2)

In [77]:
a+eval('b')

('1', 1, '2', 2)

In [80]:
a="fdfd"+str([1,2,3])

In [82]:
a=''

In [83]:
not a

True

In [84]:
class Test():
    pass

In [88]:
Test.__name__

'Test'

In [89]:
a='\r\n'
len(a)

2

In [90]:
len(a.strip())

0

In [92]:
[i for i in range(1,1)]

[]

In [93]:
a=Test()
a.a=1

In [94]:
a.a

1

In [124]:
a={"a":1,"b":2,"c":3}

In [125]:
def test(a=b,b=a,d=None,c=None):
    print(a,b,d,c)
test(1,2)

1 2 None None


In [126]:
test(**a)

1 2 None 3


In [104]:
import numpy as np

In [212]:
a=np.array([[2.1,3.0],[5.1,7.1],[1.1,0.0],[3.0,4.0]])
b=np.array([1,0,1,1])
c=(b==0)
c.sum()

1

In [213]:
d=np.argmax(a,axis=1)
d

array([1, 1, 0, 1])

In [238]:
a,b

(array([[2.1, 3. ],
        [5.1, 7.1],
        [1.1, 0. ],
        [3. , 4. ]]), array([1, 0, 1, 1]))

SyntaxError: invalid syntax (<ipython-input-226-1971d7064c5a>, line 1)

In [230]:
import torch.nn as nn
import torch
from torch import float32
loss_fct = nn.CrossEntropyLoss()

In [239]:
c1=torch.tensor(a,dtype=float32).view(-1,2)
c2=torch.tensor([[0.0],[1.0],[0.0],[1.0]],dtype=float32).view(-1)
c1,c2

(tensor([[2.1000, 3.0000],
         [5.1000, 7.1000],
         [1.1000, 0.0000],
         [3.0000, 4.0000]]), tensor([0., 1., 0., 1.]))

In [244]:
s=nn.LogSigmoid()
s(c1)

tensor([[-0.1155, -0.0486],
        [-0.0061, -0.0008],
        [-0.2873, -0.6931],
        [-0.0486, -0.0181]])